version: '3.7'
services:
  api:
    container_name: oidc-example-api-with-frontend
    environment:
      - CLIENT_ID=quarkus
      - KEYCLOAK_URL=http://identity:8080
    image: "quarkus/oidc-example-jvm:latest"
    links:
      - identity
    ports:
      - "80:8080"
    networks:
      - bridge
    depends_on:
      - identity
    command: ["dockerize -wait http://identity:8080/auth"]
    restart: on-failure
  identity:
    container_name: oidc-example-keycloak
    image: "jboss/keycloak:latest"
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
    expose:
      - "8080"
    ports:
      - "8000:8080"
    networks:
      - bridge
networks:
  bridge:
    driver: bridge
